[2025-07-23T09:22:36.956+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: bitcoin_price_dag.fetch_bitcoin_price scheduled__2025-07-23T08:30:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
